# Generated by Django 5.2.5 on 2025-09-02 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name',
                 models.CharField(help_text='Укажите имя исполнителя', max_length=100, verbose_name='Имя')),
                ('last_name',
                 models.CharField(help_text='Укажите фамилию исполнителя', max_length=150, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title',
                 models.CharField(help_text='Укажите название песни', max_length=250, verbose_name='Название песни')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Напишите название альбома', max_length=255,
                                           verbose_name='Название альбома')),
                ('release_year',
                 models.PositiveIntegerField(help_text='Укажите год выпуска', verbose_name='Год выпуска')),
                ('artist',
                 models.ForeignKey(help_text='Укажите исполнителя альбома',
                                   on_delete=django.db.models.deletion.CASCADE,
                                   related_name='albums', to='songs.artist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.PositiveIntegerField(help_text='Укажите порядковый номер',
                                                             verbose_name='Порядковый номер в альбоме')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.album',
                                            verbose_name='Альбом')),
                ('song',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song',
                                   verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'unique_together': {('album', 'song'), ('album', 'track_number')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(help_text='Укажите альбомы', related_name='songs', through='songs.Track',
                                         to='songs.album', verbose_name='Альбомы'),
        ),
    ]
